# Q2. Row Echelon Form:
Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its Row Echelon Form by performing elementary row operations.

In [1]:
# Set the random seed using the last two digits of your roll number
# Replace 45 with the last two digits of your roll number
import numpy as np
np.random.seed(40)
A = np.random.randint(0, 10, size=(5, 5))
print(" Matrix A:")
print(A)

 Matrix A:
[[6 7 5 8 8]
 [2 1 7 2 3]
 [7 3 9 0 1]
 [5 9 8 4 4]
 [8 6 3 3 7]]


In [2]:
#Reduced row echelon form using elementary row operations
rows, cols = A.shape
for i in range(min(rows, cols)):
    # Find the pivot element
    pivot_row = i
    while pivot_row < rows and A[pivot_row, i] == 0:
        pivot_row += 1
    if pivot_row == rows: 
        continue
    # Swap rows to bring pivot element to the diagonal
    A[[i, pivot_row]] = A[[pivot_row, i]]
    A[i] = A[i] / A[i, i]
    for j in range(i + 1, rows):
        A[j] = A[j] - A[j, i] * A[i]

print("\nRow Echelon Form of Matrix A:")
print(A)


Row Echelon Form of Matrix A:
[[ 1  1  0  1  1]
 [ 0  1 -7  0 -1]
 [ 0  0  1  0  0]
 [ 0  0  0  1 -3]
 [ 0  0  0  0  1]]
